"use strict";
var copier = require("../../copier");
var lessCompiler = require("../../lessCompiler");
/**
 *
 * @param {requestContext.RequestContext} rc
 */
module.exports=function (rc) {
    var projDir = rc.runtime.constructProjectPath("");
    var lessFiles = copier.listDirChildrenFullPathsRecursively(projDir).filter(function(p){
        var suffix = "-compiled.css";
        return p.indexOf(suffix) === (p.length - suffix.length);
    });
    var deleted = lessCompiler.deleteAllCompiledCssFiles(lessFiles);
    console.log("Deleted compiled less files : ", deleted);
    rc.response.writeHead(200, {
        "Content-Type":"text/html; charset=utf8"
    });
    rc.response.write('<p>This is the intentionally blank page after deleting all autogenerated *-compiled.css files if corresponding *.less file exists</p><p>Going <a href="/">Home</a> might trigger recompilation thus recreating the *-compiled.css files :-)</p>');
    rc.response.end();
};
module.exports.label = 'Delete Compiled lesscss';
module.exports.description = 'Deletes all CSS files that are the result of automatically ';